var html2 = "<div class=\"contain\">";
html2 += "                <div class=\"nameIn\">";
html2 += "                    <img src=\"images/faceImg.png\" class=\"faceImg\" />";
html2 += "                    <div class=\"nameFont\">Mr. Williams</div>";
html2 += "                    <div class=\"erweima\">";
html2 += "                        <img src=\"images/erweima.png\" />";
html2 += "                    </div>";
html2 += "                    <div class=\"bb\">新浪微博：教雅思的袋鼠国人</div>";
html2 += "                    <div class=\"gg\">扫一扫二维码图案，关注我吧</div>";
html2 += "                </div>";
html2 += "                <div class=\"centerImg\">";
html2 += "                    <div class=\"teacherIntro\">";
html2 += "                        <div class=\"title\">名师介绍</div>";
html2 += "                        <div class=\"content\">";
html2 += "                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;出生于澳大利亚的日裔，前雅思考官、剑桥大学国际英语";
html2 += "                            培训师、英语教学研究资深专家。1995年至今专职从事雅思阅";
html2 += "                            卷、教学和培训工作。1999年来华，在北大学中文同时在北大";
html2 += "                            教英语，先后担任国内多家知名英语培训机构雅思领军人物。";
html2 += "                            威廉老师流利的中文运用能力，使他有别于普通的外教，而他";
html2 += "                            纯正的英语背景，又更胜国内的许多培训名师一筹。他独创的";
html2 += "                            SARS词汇记忆法、FATPC高速阅读法、QPS口语有效表达法和";
html2 += "                            PREP捷径写作法，已经成为广大雅思低分考生突破6分瓶颈、";
html2 += "                            获得高分的“杀手锏”。";
html2 += "                        </div>";
html2 += "                    </div>";
html2 += "                </div>";
html2 += "                <div class=\"t-in-Img\">";
html2 += "                    <img src=\"images/teacherIm.png\" />";
html2 += "                </div>";
html2 += "            </div>";

var html3 = "";
html3 += "             <div class=\"contain\">";
html3 += "                 <div class=\"centerImg\">";
html3 += "                     <div class=\"teacherIntro\">";
html3 += "                         <div class=\"title\">适合群体</div>";
html3 += "                         <div class=\"content\">";
html3 += "                             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;所有准备参加雅思<span class=\"greenFont\">A类</span>和<span class=\"greenFont\">G类</span>考试的学员。如果你对雅思考试的评分标";
html3 += "                             准还不了解；如果你在口语考试时思绪混乱不知如何开口回答；如果你对小";
html3 += "                             作文各种数据流程不知所措；如果你大作文结构混乱，不懂如何展开分论点";
html3 += "                             ，不懂逻辑层次扩展；如果你在雅思考试口语写作部分一直突破不了6.5分；";
html3 += "                             那么你可以在这次课程里找到所有问题答案！";
html3 += " ";
html3 += "                         </div>";
html3 += "                     </div>";
html3 += "                 </div>";
html3 += "                 <div class=\"t-in-Img\">";
html3 += "                     <img src=\"images/appUser.png\" />";
html3 += "                 </div>";
html3 += "                 <div class=\"appUserImg\">";
html3 += "                     <img src=\"images/appUserImg.png\" />";
html3 += "                 </div>";
html3 += "             </div>";

var html4 = "";
html4 += "";
html4 += "            <div class=\"contain\">";
html4 += "                <div class=\"centerImg\">";
html4 += "                    <div class=\"teacherIntro\">";
html4 += "                        <div class=\"title\">课程特色</div>";
html4 += "                        <div class=\"content\">";
html4 += "                            <ul>";
html4 += "                                <li class=\"li1\"><i></i>小班制上课，注重课堂互动，人人都有机会开口练习，获得老师指点</li>";
html4 += "                                <li class=\"li2\"><i></i>从雅思考试评分标准入手，让你真正了解雅思考试，快速突破瓶颈</li>";
html4 += "                                <li class=\"li3\"><i></i>涵盖所有雅思口语考试热门考点，考试题型深度讲解及思路拓展</li>";
html4 += "                                <li class=\"li4\"><i></i>雅思小作文六大题型全面解析，看懂数据，明确对比阐述变化，读懂流程，花样表达巧妙连接</li>";
html4 += "                                <li class=\"li5\"><i></i>雅思大作文八大题型全面解析，打破套路，轻松搞定文章脉络；头脑风暴，充分拓展论点论据</li>";
html4 += "                                <li class=\"li6\"><i></i>课前发放题型素材宝典，课后布置练习题目，科学备考，快速消化吸收每堂课所学内容。</li>";
html4 += "                            </ul>";
html4 += "";
html4 += "                        </div>";
html4 += "                    </div>";
html4 += "                </div>";
html4 += "                <div class=\"t-in-Img\">";
html4 += "                    <img src=\"images/courserFont.png\" />";
html4 += "                </div>";
html4 += "                <div class=\"rulerImg\">";
html4 += "                    <img src=\"images/rulerImg.png\" />";
html4 += "                </div>";
html4 += "                <div class=\"bookImg\">";
html4 += "                    <img src=\"images/book.png\" />";
html4 += "                </div>";
html4 += "            </div>";


var html5 = "";
html5 += "";
html5 += "            <div class=\"containPage5\">";
html5 += "                <div class=\"centerImgPage5\">";
html5 += "                    <div class=\"teacherIntro\">";
html5 += "                        <div class=\"title\">学员评价</div>";
html5 += "                        <div class=\"content\">";
html5 += "                            <ul>";
html5 += "                                <li class=\"full\">";
html5 += "                                    <div class=\"left imgface\">";
html5 += "                                        <img src=\"images/face/imgA.png\" />";
html5 += "                                        <br />";
html5 += "                                        <div class=\"name\">郭同学</div>";
html5 += "                                    </div>";
html5 += "                                    <div class=\"left contentFont\">";
html5 += "                                        因为工作的原因，没有按时参加所有的课程。细心的老师在课后会第一时间把课程录音和";
html5 += "                                        讲义发给我，还有课堂上老师的一些笔记。最后一节课后还是有很多不舍的，william老师";
html5 += "                                        身体没有完全好就给我上课，很感动~课堂上，按照william老师的思路走，能创造出属于";
html5 += "                                        自己的句子和答案，而不是生硬的模板~ 感谢william老师，支持人人留学~";
html5 += "                                        <!--<div class=\"numDv\">";
html5 += "                                                <i class=\"like\"></i>";
html5 += "                                                <i class=\"nolike\"></i>";
html5 += "                                                <span>+150</span>";
html5 += "                                            </div>-->";
html5 += "                                    </div>";
html5 += "                                    <div class=\"clear\"></div>";
html5 += "                                </li>";
html5 += "                                <li>";
html5 += "                                    <div class=\"left imgface\">";
html5 += "                                        <img src=\"images/face/imgB.png\" />";
html5 += "                                        <br />";
html5 += "                                        <div class=\"name\">张同学</div>";
html5 += "                                    </div>";
html5 += "                                    <div class=\"left contentFont\">";
html5 += "                                        威廉老师的雅思课程非常实用，更幸运的是能够在课堂上一对一地和老师进行互动，享受";
html5 += "                                        老师专业的点评。同时，老师也非常的负责，每周三次，一次三小时的课程，最后也让老";
html5 += "                                        师自己身体也吃不消，希望人人留学在今后的课程中能缩短上课时间，让我们能够有时间";
html5 += "                                        好好消化老师每堂课的知识点。感谢人人留学！";
html5 += "                                        <!--<div class=\"numDv\">";
html5 += "                                                <i class=\"like\"></i>";
html5 += "                                                <i class=\"nolike\"></i>";
html5 += "                                                <span>+150</span>";
html5 += "                                            </div>-->";
html5 += "                                    </div>";
html5 += "                                    <div class=\"clear\"></div>";
html5 += "                                </li>";
html5 += "                                <li class=\"maxHe\">";
html5 += "                                    <div class=\"left imgface\">";
html5 += "                                        <img src=\"images/face/imgC.png\" />";
html5 += "                                        <br />";
html5 += "                                        <div class=\"name\">廖同学</div>";
html5 += "                                    </div>";
html5 += "                                    <div class=\"left contentFont\">";
html5 += "                                        第一次参加雅思，第一次参加雅思培训班，第一次完整地参加网络课程，第一次主动地学习";
html5 += "                                        ……太多的第一次献给了人人留学雅思培训。……我刚考完口语那天正好晚上还有最后一节课";
html5 += "                                        ，我当时的心理活动就是我真的要好好感谢人人留学和威廉老师。那是因为在考试的过程中";
html5 += "                                        ，我对于考官的问题应答如流，这是我在一个月之前无法想象且不能达到的，因为从第一节";
html5 += "                                        课的录音中可以听出我是连part1都说不了三句以上，而到如今，只要part1题目一上来，瞬";
html5 += "                                        间脑海里出现威廉老师讲过的思路，马上至少三句就脱口而出。在作文方面，经过威廉老师";
html5 += "                                        的解析和四篇练习之后，我在考试时写task1就真的只用了20 分钟，所以如果要是没有威廉";
html5 += "                                        老师的解析，就可想而知我考试时写作文的状况。";
html5 += "                                        <!--<div class=\"numDv\">";
html5 += "                                                <i class=\"like\"></i>";
html5 += "                                                <i class=\"nolike\"></i>";
html5 += "                                                <span>+150</span>";
html5 += "                                            </div>-->";
html5 += "                                    </div>";
html5 += "                                    <div class=\"clear\"></div>";
html5 += "                                </li>";
html5 += "                                <li>";
html5 += "                                    <div class=\"left imgface\">";
html5 += "                                        <img src=\"images/face/imgD.png\" />";
html5 += "                                        <br />";
html5 += "                                        <div class=\"name\">苏同学</div>";
html5 += "                                    </div>";
html5 += "                                    <div class=\"left contentFont\">";
html5 += "                                        上过无数培训，然后觉得威廉老师讲的确实有用。";
html5 += "                                        <!--<div class=\"numDv\">";
html5 += "                                                <i class=\"like\"></i>";
html5 += "                                                <i class=\"nolike\"></i>";
html5 += "                                                <span>+150</span>";
html5 += "                                            </div>-->";
html5 += "                                    </div>";
html5 += "                                    <div class=\"clear\"></div>";
html5 += "                                </li>";
html5 += "                            </ul>";
html5 += "                        </div>";
html5 += "                    </div>";
html5 += "                </div>";
html5 += "                <div class=\"t-in-ImgPage5\">";
html5 += "                    <img src=\"images/studentAs.png\" />";
html5 += "                </div>";
html5 += "            </div>";

var html6 = "";
html6 += "<div class=\"containPage6\">";
html6 += "                <div class=\"nav-contral\">";
html6 += "                    <img src=\"images/leftArrow.png\" class=\"leftImg\" />";
html6 += "                    <img src=\"images/rightArrow.png\" class=\"rightImg\" />";
html6 += "                </div>";
html6 += "                <div class=\"centerImg\">";
html6 += "                    <div class=\"dvOverShow\">";
html6 += "                        <div class=\"teacherIntro\">";
html6 += "                            <div style=\"line-height: 180%\">";
html6 += "                                <div class=\"title\">课程安排</div>";
html6 += "                                <div>（一）口语课程安排</div>";
html6 += "                                <div>授课老师：<font color=\"#f88d24\">Mr. William</font>  授课时间：<font color=\"#f88d24\">19：00-20：00</font> </div>";
html6 += "                            </div>";
html6 += "                            <div class=\"content\">";
html6 += "                                <div class=\"blackBg\">";
html6 += "                                    <div class=\"dv1\">授课日期</div>";
html6 += "                                    <div class=\"dv2\">雅思口语授课主题</div>";
html6 += "                                    <div class=\"clear\"></div>";
html6 += "                                </div>";
html6 += "                                <div class=\"rowDv\">";
html6 += "                                    <div class=\"dv1\">2015-07-15  (W)</div>";
html6 += "                                    <div class=\"dv2\">1.   Fit and Healthy   强体健身</div>";
html6 += "                                    <div class=\"clear\"></div>";
html6 += "                                </div>";
html6 += "                                <div class=\"rowDv\">";
html6 += "                                    <div class=\"dv1\">2015-07-17  (W)</div>";
html6 += "                                    <div class=\"dv2\">2.   Eating Habits   饮食习惯</div>";
html6 += "                                    <div class=\"clear\"></div>";
html6 += "                                </div>";
html6 += "                                <div class=\"rowDv\">";
html6 += "                                    <div class=\"dv1\">2015-07-20  (M) </div>";
html6 += "                                    <div class=\"dv2\">3.   Before and Now   今非昔比</div>";
html6 += "                                    <div class=\"clear\"></div>";
html6 += "                                </div>";
html6 += "                                <div class=\"rowDv\">";
html6 += "                                    <div class=\"dv1\">2015-07-24  (F)  </div>";
html6 += "                                    <div class=\"dv2\">4.   The Rich and The Poor   贫富不均</div>";
html6 += "                                    <div class=\"clear\"></div>";
html6 += "                                </div>";
html6 += "                                <div class=\"rowDv\">";
html6 += "                                    <div class=\"dv1\">2015-07-27  (M)   </div>";
html6 += "                                    <div class=\"dv2\">5.   Hobbies and Interests   兴趣爱好</div>";
html6 += "                                    <div class=\"clear\"></div>";
html6 += "                                </div>";
html6 += "                                <div class=\"rowDv\">";
html6 += "                                    <div class=\"dv1\">2015-07-31  (F)  </div>";
html6 += "                                    <div class=\"dv2\">6.   A Matter of Taste   艺术审美</div>";
html6 += "                                    <div class=\"clear\"></div>";
html6 += "                                </div>";
html6 += "                                <div class=\"rowDv\">";
html6 += "                                    <div class=\"dv1\">2015-08-03  (M)</div>";
html6 += "                                    <div class=\"dv2\">7.   Energies and Natural Resources   物产能源</div>";
html6 += "                                    <div class=\"clear\"></div>";
html6 += "                                </div>";
html6 += "                                <div class=\"rowDv\">";
html6 += "                                    <div class=\"dv1\">2015-08-07  (F) </div>";
html6 += "                                    <div class=\"dv2\">8.   Our Mother Earth   地球母亲</div>";
html6 += "                                    <div class=\"clear\"></div>";
html6 += "                                </div>";
html6 += "                                <div class=\"rowDv\">";
html6 += "                                    <div class=\"dv1\">2015-08-10  (M)</div>";
html6 += "                                    <div class=\"dv2\">9.   Live and Learn   学习生涯</div>";
html6 += "                                    <div class=\"clear\"></div>";
html6 += "                                </div>";
html6 += "                                <div class=\"rowDv\">";
html6 += "                                    <div class=\"dv1\">2015-08-14  (F) </div>";
html6 += "                                    <div class=\"dv2\">10. Effective Communication   有效沟通</div>";
html6 += "                                    <div class=\"clear\"></div>";
html6 += "                                </div>";
html6 += "                                <div class=\"rowDv\">";
html6 += "                                    <div class=\"dv1\">2015-08-17  (M)</div>";
html6 += "                                    <div class=\"dv2\">11. Science and Men   科学与人</div>";
html6 += "                                    <div class=\"clear\"></div>";
html6 += "                                </div>";
html6 += "                                <div class=\"rowDv\">";
html6 += "                                    <div class=\"dv1\">2015-08-21  (F)</div>";
html6 += "                                    <div class=\"dv2\">12. The World on Move   交通出行</div>";
html6 += "                                    <div class=\"clear\"></div>";
html6 += "                                </div>";
html6 += "                                <div class=\"rowDv\">";
html6 += "                                    <div class=\"dv1\">2015-08-24  (M)</div>";
html6 += "                                    <div class=\"dv2\">13. Leading the fashion   引领时尚</div>";
html6 += "                                    <div class=\"clear\"></div>";
html6 += "                                </div>";
html6 += "                                <div class=\"rowDv\">";
html6 += "                                    <div class=\"dv1\">2015-08-28  (F)</div>";
html6 += "                                    <div class=\"dv2\">14. Law has a long arm   法网恢恢</div>";
html6 += "                                    <div class=\"clear\"></div>";
html6 += "                                </div>";
html6 += "                                <div class=\"rowDv\">";
html6 += "                                    <div class=\"dv1\">2015-08-31  (M)</div>";
html6 += "                                    <div class=\"dv2\">15. The Media and the Vanity   传媒名利</div>";
html6 += "                                    <div class=\"clear\"></div>";
html6 += "                                </div>";
html6 += "                                <div class=\"rowDv\">";
html6 += "                                    <div class=\"dv1\">2015-09-04  (F)</div>";
html6 += "                                    <div class=\"dv2\">16. Getting down to business and work   职场商海</div>";
html6 += "                                    <div class=\"clear\"></div>";
html6 += "                                </div>";
html6 += "                            </div>";
html6 += "                        </div>";
html6 += "                        <div class=\"teacherIntro\">";
html6 += "                            <div style=\"line-height: 180%\">";
html6 += "                                <div class=\"title\">课程安排</div>";
html6 += "                                <div>（二）写作课程安排</div>";
html6 += "                                <div>授课老师：<font color=\"#f88d24\">Mr. William</font>授课时间：<br/><font color=\"#f88d24\">(周六 s)09：45-10：30|(周三 w)19：00-19：45</font></div>";
html6 += "                            </div>";
html6 += "                            <div class=\"content\">";
html6 += "                                <div class=\"blackBg\">";
html6 += "                                    <div class=\"dv1\">授课日期</div>";
html6 += "                                    <div class=\"dv2\">雅思写作授课主题</div>";
html6 += "                                    <div class=\"clear\"></div>";
html6 += "                                </div>";
html6 += "                                <div class=\"rowDv\">";
html6 += "                                    <div class=\"dv1\">2015-07-18  (S)</div>";
html6 += "                                    <div class=\"dv2\">Task 2 – Problem/Causes/Solution essay  问题-原因-解决方案类</div>";
html6 += "                                    <div class=\"clear\"></div>";
html6 += "                                </div>";
html6 += "                                <div class=\"rowDv\">";
html6 += "                                    <div class=\"dv1\">2015-07-22  (W)</div>";
html6 += "                                    <div class=\"dv2\">Task 1 – Line graph  线状图写作</div>";
html6 += "                                    <div class=\"clear\"></div>";
html6 += "                                </div>";
html6 += "                                <div class=\"rowDv\">";
html6 += "                                    <div class=\"dv1\">2015-07-25  (S)</div>";
html6 += "                                    <div class=\"dv2\">Task 1 – Bar chart  柱状图写作</div>";
html6 += "                                    <div class=\"clear\"></div>";
html6 += "                                </div>";
html6 += "                                <div class=\"rowDv\">";
html6 += "                                    <div class=\"dv1\">2015-07-29  (W)</div>";
html6 += "                                    <div class=\"dv2\">Task 2 – Argument for and against essay  支持和反对观点类</div>";
html6 += "                                    <div class=\"clear\"></div>";
html6 += "                                </div>";
html6 += "                                <div class=\"rowDv\">";
html6 += "                                    <div class=\"dv1\">2015-08-01  (S)</div>";
html6 += "                                    <div class=\"dv2\">Task 1 – Table  表格图写作</div>";
html6 += "                                    <div class=\"clear\"></div>";
html6 += "                                </div>";
html6 += "                                <div class=\"rowDv\">";
html6 += "                                    <div class=\"dv1\">2015-08-05  (W)</div>";
html6 += "                                    <div class=\"dv2\">Task 2 – Discursive essay (1)  讨论类(1)</div>";
html6 += "                                    <div class=\"clear\"></div>";
html6 += "                                </div>";
html6 += "                                <div class=\"rowDv\">";
html6 += "                                    <div class=\"dv1\">2015-08-08  (S)</div>";
html6 += "                                    <div class=\"dv2\">Task 1 – Pie chart –  饼图写作</div>";
html6 += "                                    <div class=\"clear\"></div>";
html6 += "                                </div>";
html6 += "                                <div class=\"rowDv\">";
html6 += "                                    <div class=\"dv1\">2015-08-12  (W)</div>";
html6 += "                                    <div class=\"dv2\">Task 2 – Discursive essay (2)  讨论类(2)</div>";
html6 += "                                    <div class=\"clear\"></div>";
html6 += "                                </div>";
html6 += "                                <div class=\"rowDv\">";
html6 += "                                    <div class=\"dv1\">2015-08-15  (S)</div>";
html6 += "                                    <div class=\"dv2\">Task 1 – Flow Chart –  流程图写作</div>";
html6 += "                                    <div class=\"clear\"></div>";
html6 += "                                </div>";
html6 += "                                <div class=\"rowDv\">";
html6 += "                                    <div class=\"dv1\">2015-08-19  (W)</div>";
html6 += "                                    <div class=\"dv2\">Task 2 – Pros and Cons essay  讨论优劣类</div>";
html6 += "                                    <div class=\"clear\"></div>";
html6 += "                                </div>";
html6 += "                                <div class=\"rowDv\">";
html6 += "                                    <div class=\"dv1\">2015-08-22  (S)</div>";
html6 += "                                    <div class=\"dv2\">Task 2 – Comparison essay  比较类</div>";
html6 += "                                    <div class=\"clear\"></div>";
html6 += "                                </div>";
html6 += "                                <div class=\"rowDv\">";
html6 += "                                    <div class=\"dv1\">2015-08-26  (W)</div>";
html6 += "                                    <div class=\"dv2\">Task 1 – Map  地图写作</div>";
html6 += "                                    <div class=\"clear\"></div>";
html6 += "                                </div>";
html6 += "                                <div class=\"rowDv\">";
html6 += "                                    <div class=\"dv1\">2015-08-29  (S)</div>";
html6 += "                                    <div class=\"dv2\">Task 2 – Expository essay –  说明阐述类</div>";
html6 += "                                    <div class=\"clear\"></div>";
html6 += "                                </div>";
html6 += "                                <div class=\"rowDv\">";
html6 += "                                    <div class=\"dv1\">2015-09-02(W)</div>";
html6 += "                                    <div class=\"dv2\">Task 2 – Multiple Tasks –  多重任务类</div>";
html6 += "                                    <div class=\"clear\"></div>";
html6 += "                                </div>";
html6 += "                            </div>";
html6 += "                        </div>";
html6 += "                    </div>";
html6 += "                </div>";
html6 += "                <div class=\"t-in-Img\">";
html6 += "                    <img src=\"images/schedule.png\" />";
html6 += "                </div>";
html6 += "            </div>";

var html7 = "";
html7 += "<div class=\"contain\">";
html7 += "                <div class=\"centerImg\">";
html7 += "                    <div class=\"teacherIntro\">";
html7 += "                        <div class=\"title\">资讯报名</div>";
html7 += "                        <div class=\"content\" id=\"fillInform\">";
html7 += "                            <div class=\"inputDv\">";
html7 += "                                <input type=\"text\" placeholder=\"姓名\" />";
html7 += "                            </div>";
html7 += "                            <div class=\"inputDv\">";
html7 += "                                <input type=\"text\" placeholder=\"手机\" />";
html7 += "                            </div>";
html7 += "                            <div class=\"inputDv\">";
html7 += "                                <input type=\"text\" placeholder=\"QQ\" />";
html7 += "                            </div>";
html7 += "                            <div class=\"inputDv\">";
html7 += "                                <input type=\"text\" placeholder=\"学历\" />";
html7 += "                            </div>";
html7 += "                            <div class=\"btnDv\">";
html7 += "                                <button id=\"confirmForm\">确认</button>";
html7 += "                            </div>";
html7 += "                        </div>";
html7 += "                    </div>";
html7 += "                </div>";
html7 += "            </div>";